import { BusinessActivity, BusinessCustomer, BusinessEvent, MarketplaceItem, BusinessNotification } from './businessTypes';

export const INITIAL_BUSINESS_ACTIVITIES: BusinessActivity[] = [
  {
    id: 'act_1',
    type: 'payment_received',
    title: 'Payment Received',
    subtitle: 'M-Pesa Express from Kwame Mensah',
    amount: '+$120.00',
    status: 'Settled',
    statusColor: 'emerald',
    timestamp: '10 mins ago',
    customerName: 'Kwame Mensah',
    customerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    referenceId: 'MP-TXN-88412',
    paymentMethod: 'M-Pesa (Kenya)',
    items: 'Handwoven Kente Statement Jacket (Medium)',
  },
  {
    id: 'act_2',
    type: 'invoice_paid',
    title: 'Invoice Settled',
    subtitle: 'Invoice #INV-8492 paid by Brian Kiprono',
    amount: '+$340.00',
    status: 'Settled',
    statusColor: 'emerald',
    timestamp: '1 hour ago',
    customerName: 'Brian Kiprono',
    customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    referenceId: 'INV-8492-KE',
    paymentMethod: 'Card (Visa / Mastercard)',
    items: '4x Ankara & Top-Grain Leather Laptop Sleeves (Bulk order)',
  },
  {
    id: 'act_3',
    type: 'new_customer',
    title: 'New VIP Customer',
    subtitle: 'Amina Diallo joined from Accra, Ghana',
    status: 'Active',
    statusColor: 'purple',
    timestamp: '3 hours ago',
    customerName: 'Amina Diallo',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    referenceId: 'CUST-ACC-299',
    items: 'Saved 3 items from AfroArtisan catalog',
  },
  {
    id: 'act_4',
    type: 'order_dispatched',
    title: 'Order Dispatched',
    subtitle: 'DHL Express tracking assigned to #AFRO-7782',
    amount: '$85.00',
    status: 'Dispatched',
    statusColor: 'blue',
    timestamp: '5 hours ago',
    customerName: 'Zainab Al-Mansoor',
    customerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    referenceId: 'DHL-AFR-90211',
    paymentMethod: 'MTN Mobile Money',
    items: '1x Kente Statement Jacket (Medium) to Lagos',
  },
  {
    id: 'act_5',
    type: 'product_listed',
    title: 'New Product Listed',
    subtitle: 'Handcrafted Kente Statement Jacket published to catalog',
    status: 'Completed',
    statusColor: 'amber',
    timestamp: 'Yesterday',
    referenceId: 'CAT-PROD-001',
    items: 'Inventory stock set to 15 units • M-Pesa enabled',
  },
];

export const INITIAL_BUSINESS_CUSTOMERS: BusinessCustomer[] = [
  {
    id: 'cust_1',
    name: 'Kwame Mensah',
    handle: '@kwame:wat.chat',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    location: 'Accra, Ghana',
    tier: 'VIP',
    totalSpent: 1280,
    ordersCount: 9,
    lastOrderDate: 'Today',
    preferredPayment: 'M-Pesa / MTN MoMo',
  },
  {
    id: 'cust_2',
    name: 'Brian Kiprono',
    handle: '@brian:wat.chat',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    location: 'Nairobi, Kenya',
    tier: 'Wholesale',
    totalSpent: 2450,
    ordersCount: 14,
    lastOrderDate: 'Yesterday',
    preferredPayment: 'M-Pesa Express',
  },
  {
    id: 'cust_3',
    name: 'Amina Diallo',
    handle: '@amina:wat.chat',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    location: 'Dakar, Senegal',
    tier: 'Regular',
    totalSpent: 420,
    ordersCount: 3,
    lastOrderDate: '3 days ago',
    preferredPayment: 'Orange Money / Wave',
  },
  {
    id: 'cust_4',
    name: 'Zainab Al-Mansoor',
    handle: '@zainab:wat.chat',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    location: 'Cairo, Egypt',
    tier: 'VIP',
    totalSpent: 1890,
    ordersCount: 8,
    lastOrderDate: '5 days ago',
    preferredPayment: 'International Card',
  },
];

export const INITIAL_BUSINESS_EVENTS: BusinessEvent[] = [
  {
    id: 'evt_1',
    title: 'Pan-African E-Commerce & Artisan Trade Expo',
    date: 'Oct 14 - 16, 2026',
    time: '09:00 AM - 05:00 PM GMT',
    location: 'Kigali Convention Centre & Virtual LiveStream',
    organizer: 'African Trade Guild & WAT Commerce',
    attendeesCount: 2480,
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    category: 'Trade Expo',
    price: 'Free Entry',
    description: 'Connect with 500+ verified suppliers, discover cross-border logistics routes, and meet mobile money payment processors.',
  },
  {
    id: 'evt_2',
    title: 'Masterclass: Scaling African Fashion to Global Markets',
    date: 'Nov 02, 2026',
    time: '02:00 PM - 04:30 PM EAT',
    location: 'Nairobi Creative Hub (Jitsi SFU Room)',
    organizer: 'AfroArtisan Collective',
    attendeesCount: 820,
    image: 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=800&auto=format&fit=crop&q=80',
    category: 'Workshop',
    price: '$25.00 / 3,200 KES',
    description: 'Learn sustainable textile sourcing, export documentation, and conversational checkout integrations on WAT.',
  },
  {
    id: 'evt_3',
    title: 'Nairobi Artisan Pop-Up & Live Craft Exhibition',
    date: 'Nov 19, 2026',
    time: '10:00 AM - 06:00 PM EAT',
    location: 'The Alchemist, Westlands, Nairobi',
    organizer: 'Kenya Handmade Guild',
    attendeesCount: 1450,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80',
    category: 'Networking',
    price: 'Free RSVP',
    description: 'A physical gathering of artisans, jewelers, and specialty coffee roasters featuring instant tap-to-pay WAT QR checkouts.',
  },
];

export const INITIAL_MARKETPLACE_ITEMS: MarketplaceItem[] = [
  {
    id: 'mkt_1',
    title: 'Hand-Carved Soapstone Chess Set (Kisii Valley)',
    seller: 'Great Rift Artisans Ltd',
    sellerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    location: 'Kisii, Kenya',
    price: 64,
    currency: 'USD',
    image: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=500&auto=format&fit=crop&q=80',
    category: 'Art & Collectibles',
    verified: true,
    minOrder: '1 Unit',
    rating: 4.9,
  },
  {
    id: 'mkt_2',
    title: 'Organic Shea Butter & Baobab Oil Trio (Wholesale Pack)',
    seller: 'Tamale Shea Women Guild',
    sellerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    location: 'Tamale, Ghana',
    price: 48,
    currency: 'USD',
    image: 'https://images.unsplash.com/photo-1608248597359-bb43ef99d750?w=500&auto=format&fit=crop&q=80',
    category: 'Beauty & Skincare',
    verified: true,
    minOrder: '5 Units',
    rating: 5.0,
  },
  {
    id: 'mkt_3',
    title: 'Woven Sisal & Leather Kiondo Basket Bags (Pack of 3)',
    seller: 'Machakos Weavers Cooperative',
    sellerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    location: 'Machakos, Kenya',
    price: 92,
    currency: 'USD',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=500&auto=format&fit=crop&q=80',
    category: 'Bags & Home Goods',
    verified: true,
    minOrder: '1 Pack',
    rating: 4.8,
  },
  {
    id: 'mkt_4',
    title: 'Single-Origin Rwandan Specialty Bourbon Beans (1kg)',
    seller: 'Huye Mountain Roasters',
    sellerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    location: 'Huye, Rwanda',
    price: 36,
    currency: 'USD',
    image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=500&auto=format&fit=crop&q=80',
    category: 'Gourmet & Coffee',
    verified: true,
    minOrder: '2 Bags',
    rating: 4.95,
  },
];

export const INITIAL_BUSINESS_NOTIFICATIONS: BusinessNotification[] = [
  {
    id: 'notif_1',
    title: 'Payment Verified: +$120.00',
    message: 'M-Pesa C2B settlement from Kwame Mensah confirmed and added to your available ledger balance.',
    timestamp: '12m ago',
    type: 'payment',
    unread: true,
  },
  {
    id: 'notif_2',
    title: 'Low Stock Alert: Raffia Shopper',
    message: 'Handwoven Natural Raffia Shopper Tote is down to 3 units in stock. Consider replenishing inventory.',
    timestamp: '1h ago',
    type: 'inventory',
    unread: true,
  },
  {
    id: 'notif_3',
    title: 'New VIP Customer Registered',
    message: 'Amina Diallo completed onboarding and tagged your store in Pan-African Design Syndicate.',
    timestamp: '3h ago',
    type: 'customer',
    unread: false,
  },
  {
    id: 'notif_4',
    title: 'Monthly Commerce Settlement Ready',
    message: 'Your automated VAT & Mobile Money tax summary statement for the past 30 days is generated.',
    timestamp: 'Yesterday',
    type: 'system',
    unread: false,
  },
];
